# Generated by Django 3.0.7 on 2021-02-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='topic',
        ),
    ]
